### ISSUE TITLE
Configuration with {rprojroot} package. 

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/tutorials#106]
When tried to run the tutorial repo on my local machine, I encountered the following error: `failed to find source for 'rprojroot 2.0.3' in package repositories. But I have installed this package  in the machine.

**Comment by Bisaloo** [comment]
@Degoot-AM, can you let me know which version of R you are using please? You can find it out by running `R.version` in your R console

**Comment by Degoot-AM** [comment]
@Bisaloo ,  R version 4.3.2 (2023-10-31), nickname `Eye Holes`
