### ISSUE TITLE
! Error installing package `RcppParallel`

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials#111]
> - we can clarify that rendering the materials is not expected from reviewers and improve the online preview mechanism.

_Originally posted by @Bisaloo in https://github.com/epiverse-trace/tutorials/issues/104#issuecomment-1906002042_

In order to generate the `md-outputs-PR-104` branch for #104 and facilitate its review, I worked on resolving the conflicts of the PR locally with a git-rebase. 

After this, I'm getting an [error while running the "Build markdown source files" gh-action](https://github.com/epiverse-trace/tutorials/actions/runs/7645188407/job/20831177559?pr=104#step:7:1545).

We previously had a [similar issue in epimodelac](https://github.com/epiverse-trace/epimodelac/pull/11#issuecomment-1837203396) repository, but doing the same action did not resolve this error message.

**Comment by Bisaloo** [comment]
Could you please try to install it from RSPM, as done in https://github.com/epiverse-trace/tutorials/pull/112?

**Comment by avallecam** [comment]
> Could you please try to install it from RSPM, as done in #112?

solved, thank you!
