### ISSUE TITLE
warning from `{lintr}` workflow in `[namespace_lintr]`

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials#119]
In #104 from workflow in https://github.com/epiverse-trace/tutorials/actions/runs/7699737505/job/20982024773?pr=104 to line:

https://github.com/epiverse-trace/tutorials/blob/a253dac10a74747b8c646f308960cdf851942924/episodes/read-delays.Rmd#L187-L190

I'm getting this `{lintr}` warning

```
Warning: file=read-delays.Rmd,line=188,col=1,[namespace_linter] Package 'epiparameter' is not installed.
```

Some thoughts:
- `epiparameter` is called and installed from the `renv.lock`. Where does `lintr` expect to find dependencies or if a package is installed?
- This is a feature we agreed on in https://github.com/epiverse-trace/episoap/issues/91, and suggested to keep using it in writing as in https://github.com/epiverse-trace/tutorials/issues/25. should we adapt to `lintr`? or adapt `lintr` to some of our features?

tagging @Bisaloo since this is related with #96

**Comment by Bisaloo** [comment]
It looks like epiparameter and epidemics and not properly installed during the lintr check. I'll look into it.

> 2024-02-01T11:11:48.6709022Z Skipping 2 packages not available: epiparameter, epidemics

**Comment by avallecam** [comment]
thank you @Bisaloo this is the only `lintr` pending to pass for #104 as in this last run https://github.com/epiverse-trace/tutorials/actions/runs/7754598773/job/21148236369?pr=104

**Comment by avallecam** [comment]
also only `lintr` pending to pass in #58 as in last run https://github.com/epiverse-trace/tutorials/actions/runs/7755166483/job/21149968993?pr=58

package highlighted is `{here}`

**Comment by avallecam** [comment]
go it, just found the [.lintr](https://github.com/epiverse-trace/tutorials/blob/main/.lintr) file! I can proceed by:
- edit this in a new PR
- request your approval to merge
- rebase PR #104 and #58 
- request your approval for them to merge

but keeping this issue open for further investigation or decision.

happy to read your suggestions about this

**Comment by avallecam** [comment]
closing as solved
