### ISSUE TITLE
evaluate benefits of suggested glossary format

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials#32]
In #24 glossary was added in alphabetical order, which facilitates manual reference.

Workbench suggests a pandoc format:
- https://carpentries.github.io/sandpaper-docs/aio.html#learners 
- https://carpentries.github.io/sandpaper-docs/reference.html#glossary 
- https://github.com/carpentries/sandpaper-docs/blob/da4586676237affabd3f696a450d08c09feab6f4/learners/reference.md?plain=1 

Does it facilitate any automatic reference or linking?

**Comment by amanda-minter** [comment]
The pandoc format does not allow for linking, in the current format we will be able to reference the 'section header' e.g. /reference.html#airborne-transmission/. 

Should we link to glossary definitions in the tutorials?

**Comment by avallecam** [comment]
Thank you for this reminder. I added this issue to do some research on the topic. 

I found an example here:
- In ([this lesson, at episode 04-changes](https://swcarpentry.github.io/git-novice/04-changes.html)) the word "changeset" is hyperlinked to its specific position in the glossary ([link](https://swcarpentry.github.io/git-novice/reference.html#changeset))
- In the raw file, that word is tagged with `[changeset](../learners/reference.md#changeset)` ([link](https://github.com/swcarpentry/git-novice/blob/main/episodes/04-changes.md?plain=1#L310))
- And in the glossary section under the reference.md file it is written with the extra tag `[changeset]{#changeset}` ([link](https://github.com/swcarpentry/git-novice/blob/main/learners/reference.md?plain=1#L16))

NOTE:
- For content out of the episodes, like the word "version control" in the setup page ([link](https://swcarpentry.github.io/git-novice/index.html)), it is tagged with a path corresponding to the location of the reference file `[version control](learners/reference.md#version-control)` ([link](https://github.com/swcarpentry/git-novice/blob/c3867a4d00d97316274ae2f6b1ec1cc0a78db616/index.md?plain=1#L15))

Now, what is the added value of this feature? This is still pending in my study of this topic. The carpentries have extensive experience on this, like in [this glosario repository](https://github.com/carpentries/glosario), so for more than one reason they may be suggesting the [Pandoc Definition List format](https://pandoc.org/MANUAL.html#definition-lists) as cited in the [sandpaper-docs](https://carpentries.github.io/sandpaper-docs/aio.html#learners). If it would rearrange the list in alphabetical order I would be surprised, hehe. Any thoughts on this @Bisaloo ?

> Should we link to glossary definitions in the tutorials?

Yes, I think we should. At least in the first mention of the concept, only. If the method above facilitates that tagging, we can opt to do it.

**Comment by amanda-minter** [comment]
Thanks for this Andree, in the example I looked at they didn't have the tags in the raw file. I think it is worth converting to pandoc because as you say, carpentries have experience and I agree we should follow there example. I'll make a PR to update the glossary to pandoc format
