### ISSUE TITLE
define contribution roles for developers, reviewers, maintainers.

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials#33]
I drafted steps for different roles in the contribution guidelines.

The goal would be to keep a homogeneous package environment among developers and reviews during review on a “development branch” different to the main.

As mentioned in #31 packages could be in continuous update, and tutorial development can try to manage that situation.

Summarized implications are:
- We will use [sandpaper::use_package_cache()](https://carpentries.github.io/sandpaper/reference/package_cache.html#background) in the project.
- The _developer_ will need to register the package version to use in a `renv.lock` file.
- The _reviewer_ will need to restore the environment defined by the Developer.
- The _maintainer_ will need to review how to automate package updates with a carpentries-bot in the main branch only.

Specific steps in:
- preview: https://github.com/epiverse-trace/tutorials/blob/main/CONTRIBUTING.md#contribution-roles
- or permalink: https://github.com/epiverse-trace/tutorials/blob/b207e3f020e177d2fcd0d972d6780fd2ace7bb46/CONTRIBUTING.md?plain=1#L74

It would be helpful to have your feedback @amanda-minter as a developer, @CarmenTamayo @pratikunterwegs as reviewers, and @Bisaloo from your expertise with workflows, if I could make this clearer or change any step.

**Comment by pratikunterwegs** [comment]
Thanks Andree - an introduction on Nov 7th sounds good.

> Now, I think in a scenario related to your question, and if not, please, I will need you to rephrase: What if the main and a dev branches have a different renv.lock file? Do we want to allow this? If yes, how to manage it? (we do not have a detailed policy for this, so happy to read team thoughts)

It will be necessary to add new packages to the lockfile on `main` from feature branches as new episodes cover new packages - such as adding {epidemics} in #34 - do you have a policy on the release status of these packages? Should they be on CRAN, or available as GH releases?

**Comment by avallecam** [comment]
> do you have a policy on the release status of these packages? Should they be on CRAN, or available as GH releases?

We will need to keep writing new episodes independent of the package release status. So, initially, we want to tolerate available GH releases, registering specific versions if needed with [pin_version](https://github.com/epiverse-trace/tutorials/blob/main/CONTRIBUTING.md#developer). (the workbench [runs actions weekly](https://github.com/epiverse-trace/research-compendium/actions) to keep the cache up to date - I still do not know what this can potentially change, like the latest SHA of a GH release?)

Now, if this is generating the job failing in #34 and will affect its merging, then this will condition us to wait for releases on CRAN. So, we can evaluate this policy after this first PR merging trial.

**Comment by avallecam** [comment]
From the [r-universe PR#12](https://github.com/epiverse-trace/epiverse-trace.r-universe.dev/pull/12) and its [action failure message](https://github.com/epiverse-trace/epiverse-trace.r-universe.dev/actions/runs/6628996731/job/18007318539), I understand that one policy on the release status of package for a successful PR merge is that it must have a GH release and available in the r-universe.

**Comment by avallecam** [comment]
> From the [r-universe PR#12](https://github.com/epiverse-trace/epiverse-trace.r-universe.dev/pull/12) and its [action failure message](https://github.com/epiverse-trace/epiverse-trace.r-universe.dev/actions/runs/6628996731/job/18007318539), Can I understand that one policy on the release status of package for a successful PR merge is that, if not on CRAN, it must fulfil two conditions (1) have a GH release and (2) be available in the r-universe?

**Rephrasing:** One policy on the release status of packages for a successful PR merge is that, if not on CRAN, it must fulfil two conditions (1) be available on GH, and (2) be available in the r-universe. 

(From the cited statement I removed the requirement of a "GH release", which I understand is not required, Can you help me confirm this @Bisaloo )

**Comment by avallecam** [comment]
> 1. I would only add that it's the developers' responsibility to keep their branches up to date with `main`, as with [Update sandpaper cache, update digest #31](https://github.com/epiverse-trace/tutorials/pull/31) once it's merged.

@pratikunterwegs , can you help me confirm if these takeaways from the experience at #34 are accurate?

- Maintainer is responsible for keeping branches up to date with `main`. 
  - Maintainer can [follow the action of "update with merge" in a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch#updating-your-pull-request-branch) to [import last commits from master](https://docs.gitlab.com/ee/topics/git/git_rebase.html).
  - However, the Maintainer should avoid doing multiple “merge branch 'main' into dev branch” during a PR. 
  - This should only be essential if the branch is having issues to compile or render, like [requested in a comment of PR 34](https://github.com/epiverse-trace/tutorials/pull/34#issuecomment-1774798882)
  - Although there is a button to do it, this is not a suggested action to do at any time the main is updated.
  - The goal is to keep the history as lines as possible, as [suggested in the blueprints](https://epiverse-trace.github.io/blueprints/git-branching-merging.html#merging-pull-requests-merge-commits-vs-squash-and-merge-vs-rebase-and-merge).
- In a PR review, the Maintainer and Developer can wait until the last review to be done to do the “Rebase and merge” at the end only.

**Comment by pratikunterwegs** [comment]
I would say you should try to keep feature branches updated with `main` as much as possible.

An exception might be if the PR is scheduled to be merged after multiple others - in that case it might be easier to update just before merging, or before asking for a review.

In general it's better to ask for reviews on stable features or fixes, as this reduces the work for reviewers in keeping track of changes.

>Maintainer can [follow the action of "update with merge" in a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch#updating-your-pull-request-branch) to [import last commits from master](https://docs.gitlab.com/ee/topics/git/git_rebase.html).

No, you should "update with rebase". Advance warning: you may or may not be able to do this online due to merge conflicts. If you have conflicts, you'll need to do this manually offline, and force-push the branch. If it does work online, your local branch will have a divergence with the remote, and you'll need to pull locally with a rebase.

**Comment by avallecam** [comment]
> > Maintainer can [follow the action of "update with merge" in a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch#updating-your-pull-request-branch) to [import last commits from master](https://docs.gitlab.com/ee/topics/git/git_rebase.html).
> 
> No, you should "update with rebase".

Yes! Update with rebase, thank you for catching that mistake. 

And now I think how I made the mistake! I was pushing the "Update branch" button, assuming that I had checked with the "Update with rebase", but the default is "Update with merge commit". I knew clearly about the rebasing, but I think the default choice beat me. Lesson learned!

**Comment by Bisaloo** [comment]
> > From the [r-universe PR#12](https://github.com/epiverse-trace/epiverse-trace.r-universe.dev/pull/12) and its [action failure message](https://github.com/epiverse-trace/epiverse-trace.r-universe.dev/actions/runs/6628996731/job/18007318539), Can I understand that one policy on the release status of package for a successful PR merge is that, if not on CRAN, it must fulfil two conditions (1) have a GH release and (2) be available in the r-universe?
> 
> **Rephrasing:** One policy on the release status of packages for a successful PR merge is that, if not on CRAN, it must fulfil two conditions (1) be available on GH, and (2) be available in the r-universe.
> 
> (From the cited statement I removed the requirement of a "GH release", which I understand is not required, Can you help me confirm this @Bisaloo )

I'm not sure what you are asking precisely. 

Our policy (but not a technical requirement) to add packages on r-universe is for them to have at least one release, either on CRAN or on GitHub. There is a GitHub Actions workflow enforcing this on PR in [epiverse-trace/epiverse-trace.r-universe.dev](https://github.com/epiverse-trace/epiverse-trace.r-universe.dev).

But this is not related to anything regarding the workbench.

**Comment by avallecam** [comment]
> Our policy (but not a technical requirement) to add packages on r-universe is for them to have at least one release, either on CRAN or on GitHub. There is a GitHub Actions workflow enforcing this on PR in [epiverse-trace/epiverse-trace.r-universe.dev](https://github.com/epiverse-trace/epiverse-trace.r-universe.dev).
> 
> But this is not related to anything regarding the workbench.

Thank you for the rephrasing. With your comment and this other comment https://github.com/carpentries/actions/issues/32#issuecomment-1777779297 I understood that the action failure came from the action for the package, but not from the workbench requirements.

Thank you all for your feedback. CONTRIBUTING file is now updated with the edit suggestion detailed in the linked issues above.
