### ISSUE TITLE
add related materials

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials#48]
in the README, similar to:
- https://epiverse-trace.github.io/episoap/#related-projects
- https://github.com/bahadzie/numberize#related-packages-and-limitations
- https://github.com/epiverse-trace/simulist/tree/related_projs#related-projects
- https://github.com/epiverse-trace/epichains/discussions/17

before
- what gap is this training material filling?

**Comment by amanda-minter** [comment]
I think it would be useful to add an 'Introduction' lesson which covers this as well as references the learner profiles

**Comment by avallecam** [comment]
> I think it would be useful to add an 'Introduction' lesson which covers this as well as references the learner profiles

Yes, this can be in the index.md file

**Comment by avallecam** [comment]
After some reviews, I now think that these links could be distracting on the front page. I think they could also be as an additional entry in the `More` tab on top, next to the `Learner Profiles` one. Plus, add a sentence and a link to the index for people interested in materials for competent practitioners.

By adding a new md file to the `learners/` folder (example of where [to add this](https://github.com/swcarpentry/git-novice/tree/main/learners)), we can create new entries to the More tab on top (example of [how it looks](https://swcarpentry.github.io/git-novice/)).

I can assign this edit to me, but first, I'm happy to read your thoughts on this.
