### ISSUE TITLE
Add learner profiles

### ISSUE THREAD

**Issue by amanda-minter** [epiverse-trace/tutorials#6]
Add learner profiles to profiles/learner-profiles.md

**Comment by avallecam** [comment]
as a reference of the learner personas to take in consideration for this material https://epiverse-trace.github.io/lessons/about.html#who-are-these-lessons-for

**Comment by amanda-minter** [comment]
Should we link to these profiles or duplicate the same text in the tutorials learner profiles?

**Comment by avallecam** [comment]
> Should we link to these profiles or duplicate the same text in the tutorials learner profiles?

Paste them as they are in the link of reference. The lesson repo will be depricated. So we can duplicate with their links to the personas repo https://epiverse-trace.github.io/personas/.
