### ISSUE TITLE
create a site to show the curricula

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials#69]
Before upgrading to [alpha stage](https://carpentries.github.io/lesson-development-training/lesson-design.html#iterative-development), we need to decide how episodes are going to be listed or organized.

The ideas to evaluate for this are:
- isolate early, middle, and late task episodes by nesting them in the website or separating them in different repos?
- locate this curricula website as an announcement site it in a [learn post](https://epiverse-trace.github.io/learn.html)?

Here are two references:
- Carpentries lessons https://software-carpentry.org/lessons/ 
- Galaxy training https://training.galaxyproject.org/training-material/topics/covid19/

**Comment by avallecam** [comment]
@Bisaloo @rozeggo, this is the issue I referred to today, and we can discuss it around January.

**Comment by Bisaloo** [comment]
https://github.com/epiverse-trace/epiverse-trace.github.io/pull/157 is related to this issue.

**Comment by avallecam** [comment]
> [epiverse-trace/epiverse-trace.github.io#157](https://github.com/epiverse-trace/epiverse-trace.github.io/pull/157) is related to this issue.

thank you, @Bisaloo 

one additional and potentially useful reference for different lessons that are connected could be the Data Carpentry [Ecology Curriculum](https://datacarpentry.org/lessons/#ecology-workshop) with one [Ecology Workshop Overview](https://datacarpentry.org/ecology-workshop/) repo that connects them all, including general the setup instructions. Additionally, the section on lessons in Spanish.

I hope this split may in the future open the possibility of having different maintainers given the different topics of focused specialization.

Regarding the tags of the new repositories, should we give them topic-specific names, or use the early/middle/late words?

idea 1:

- `early-outbreak-tutorial`
- `middle-outbreak-tutorial` 
- `late-outbreak-tutorial`

idea 2:

- `read-clean-outbreak-tutorial`
- `real-time-outbreak-tutorial`
- `scenario-modelling-outbreak-tutorial`

**Comment by avallecam** [comment]
the carpentries [instructor training](https://carpentries.github.io/instructor-training/) repo is an example of a three-day workshop with all the content in only one repo.

**Comment by avallecam** [comment]
Some ideas regarding a preliminary evaluation of a split, using the references above (Ecology curricula and Instructors training), and in two dimensions: pedagogy and maintenance. One approach when deciding about technology-enhanced learning (TEL) tools is: the discipline-specific knowledge is the one that informs the practical pedagogy (technology) in practice.

## pedagogy

**Pro:** A more spread and divided learning associated with the data analysis workflow. This will facilitate associating specific tasks within the early/middle/late classification as an interconnected process. Although the early/middle/late categorization is a continuous gradient for packages. the tasks needed are indeed more independent.

**Con:** The idea of early/middle/late as a continuous gradient for packages may be confused by a categorization. Although we agreed on the opinionated analysis pipeline when choosing the packages to use, their development and integration, the categorization in early/middle/late tasks may be arbitrary and initially unfamiliar to the community. Tutorial contributors may doubt where to place new material or limit their forking to make local derivatives.

independent idea: the roadmap notation should be a useful categorization that emphasizes its workflow process-like framework and should also be helpful for your memorabilia and understanding of how to connect packages.

## maintenance

**Pro:** split may get each piece more light in loading time. Opportunity to have different maintainers focused on the content of different groups of tutorials.

**Con:** replication or redundancy of common content across repos, like setup updates, which we are already having with the other repos (git-rstudio-basics and research-compendium). maintenance workload in solving similar issues in different repos given dependency updates.
