### ISSUE TITLE
remove install package code lines from episodes

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials#98]
#93 will partially fix this.

pending

https://github.com/epiverse-trace/tutorials/blob/215be1a16b37fcce990ae41b68de9736602a2ecb/episodes/simulating-transmission.Rmd#L16

**Comment by avallecam** [comment]
Hi @amanda-minter, does the `webshot::install_phantomjs(force = TRUE)` install a package? Or what does it do?

**Comment by amanda-minter** [comment]
It's used to ensure that the `{DiagrammeR}` widgets appear on the webpages. See info [here](https://bookdown.org/yihui/bookdown/html-widgets.html)

**Comment by avallecam** [comment]
> It's used to ensure that the `{DiagrammeR}` widgets appear on the webpages. See info [here](https://bookdown.org/yihui/bookdown/html-widgets.html)

that's really interesting, that probably can help to solve an issue reported in other of our repos https://github.com/epiverse-trace/epimodelac/issues/16 thank you for sharing the context!

**Comment by avallecam** [comment]
closing this as solved in #85

**Comment by avallecam** [comment]
used also for {epicontacts} outputs using {visNetwork} in https://github.com/epiverse-trace/tutorials-middle/pull/29/ in line https://github.com/epiverse-trace/tutorials-middle/blob/dcc9e59bce80d37b6a6408c8d0b22d75bae180c1/episodes/superspreading-estimate.Rmd#L92-L107
